repos:
  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.11.2'
    hooks:
      - id: ruff
        args: [ "--fix" ]
      - id: ruff-format
