services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: meme_user
      POSTGRES_PASSWORD: meme_password
      POSTGRES_DB: meme_god_db
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: /usr/bin/supervisord
    environment:
      - DJANGO_SETTINGS_MODULE=meme_god.settings
      - ALLOWED_HOST=localhost
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
