# Generated by Django 5.2 on 2025-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reddituser",
            name="name",
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reddituser",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
