# Generated by Django 5.2 on 2025-04-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redditpost",
            name="subreddit_subscribers",
        ),
        migrations.AddField(
            model_name="redditsub",
            name="subscribers",
            field=models.IntegerField(null=True),
        ),
    ]
