# Generated by Django 5.2 on 2025-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0002_remove_redditpost_subreddit_subscribers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditpost",
            name="pwls",
            field=models.IntegerField(null=True),
        ),
    ]
