# Generated by Django 5.2 on 2025-04-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0003_alter_redditpost_pwls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditpost",
            name="thumbnail_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="redditpost",
            name="thumbnail_width",
            field=models.IntegerField(null=True),
        ),
    ]
