# Generated by Django 5.2 on 2025-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0004_alter_redditpost_thumbnail_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditpost",
            name="url",
            field=models.URLField(max_length=255),
        ),
    ]
