# Generated by Django 5.2 on 2025-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0005_alter_redditpost_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditsub",
            name="category",
            field=models.CharField(
                choices=[
                    ("memes", "Memes"),
                    ("london", "London"),
                    ("food", "Food"),
                    ("animals", "Animals"),
                    ("china", "China"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
