# Generated by Django 5.2 on 2025-04-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0006_redditsub_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankedRedditPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking", models.FloatField(default=0)),
                (
                    "reddit_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.redditpost",
                    ),
                ),
            ],
        ),
    ]
