# Generated by Django 5.2 on 2025-04-13 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0007_rankedredditpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankedredditpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rankedredditpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
