# Generated by Django 5.2 on 2025-04-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0009_alter_rankedredditpost_reddit_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditpost",
            name="edited",
            field=models.BooleanField(null=True),
        ),
    ]
