# Generated by Django 5.2 on 2025-04-18 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0010_alter_redditpost_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankedredditpost",
            name="reddit_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="reddit.redditpost"
            ),
        ),
    ]
