# Generated by Django 5.2 on 2025-04-19 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0011_alter_rankedredditpost_reddit_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rankedredditpost",
            name="updated_at",
        ),
    ]
