# Generated by Django 5.2 on 2025-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0012_remove_rankedredditpost_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditsub",
            name="category",
            field=models.CharField(
                choices=[
                    ("memes", "Memes"),
                    ("london", "London"),
                    ("food", "Food"),
                    ("animals", "Animals"),
                    ("china", "China"),
                ],
                max_length=255,
            ),
        ),
    ]
