# Generated by Django 5.2 on 2025-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuggestedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("memes", "Memes"),
                            ("london", "London"),
                            ("food", "Food"),
                            ("animals", "Animals"),
                            ("china", "China"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(choices=[("reddit", "Reddit")], max_length=255),
                ),
                ("url", models.URLField(max_length=255)),
                ("is_video", models.BooleanField(default=False)),
                ("sent_to_telegram_at", models.DateTimeField(null=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TopicChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("memes", "Memes"),
                            ("london", "London"),
                            ("food", "Food"),
                            ("animals", "Animals"),
                            ("china", "China"),
                        ],
                        max_length=255,
                    ),
                ),
                ("channel", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
