# Generated by Django 5.2 on 2025-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_sender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedmedia",
            name="suggested",
            field=models.BooleanField(default=False),
        ),
    ]
