# Generated by Django 5.2 on 2025-04-19 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media_sender", "0002_suggestedmedia_suggested"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestedmedia",
            name="suggested",
        ),
    ]
