# Generated by Django 5.2 on 2025-04-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_sender", "0003_remove_suggestedmedia_suggested"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedmedia",
            name="sent_to_telegram",
            field=models.BooleanField(default=False),
        ),
    ]
