# Generated by Django 5.2 on 2025-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_sender", "0004_suggestedmedia_sent_to_telegram"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("memes", "Memes"),
                            ("london", "London"),
                            ("food", "Food"),
                            ("animals", "Animals"),
                            ("china", "China"),
                        ],
                        max_length=255,
                    ),
                ),
                ("channel", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="suggestedmedia",
            name="sent_to_telegram",
        ),
        migrations.AddField(
            model_name="suggestedmedia",
            name="sent_to_telegram_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="suggestedmedia",
            name="title",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suggestedmedia",
            name="source",
            field=models.CharField(
                choices=[("reddit", "Reddit")], default=None, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suggestedmedia",
            name="topic",
            field=models.CharField(
                choices=[
                    ("memes", "Memes"),
                    ("london", "London"),
                    ("food", "Food"),
                    ("animals", "Animals"),
                    ("china", "China"),
                ],
                default=None,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
